### ISSUE TITLE
Not working for Nested test classes

### ISSUE THREAD

**Issue by sickan90** [maciejwalkowiak/wiremock-spring-boot#10]
First off, great lib! Thanks!

I'm using `@Nested` for some of my test classes, but the this lib does not seems to handle it very well:
```java
@EnableWireMock({
        @ConfigureWireMock(name = "external-api", property = "application.external-api.base-url")
})
public class ExternalServiceTest extends IntegrationTest {
    @InjectWireMock("external-api")
    WireMockServer externalApiMock;

    @Nested
    @DisplayName("Test Something")
    public class TestSomething {
        @Test
        public void test1() {
            externalApiMock.stubFor(post(urlPathEqualTo("/test")).willReturn(ok())); // Throws a NullPointerException
        }
    }
}
```

However moving the annotation to the nested class works fine. So, not a blocker. However, it would be nice if this worked with nested classes in the example above.

**Comment by maciejwalkowiak** [comment]
Thanks @sickan90 for reporting! It is fixed in 1.0.2, that should appear in Maven Central in few hours.
