### ISSUE TITLE
Spring 3.2.0 Incompatibility

### ISSUE THREAD

**Issue by LitschiW** [maciejwalkowiak/wiremock-spring-boot#21]
Basically this: https://github.com/wiremock/wiremock/issues/2395

As far as I understood Spring 3.2.0 uses jetty 12 instead of 11 (which is used by wiremock), creating an incompatibility that manifests itself as:
```java
java.lang.NoClassDefFoundError: jakarta/servlet/DispatcherType
```

This is solveable by replacing the wiremock dependency with wiremock-standalone:
```xml
     <dependency>
            <groupId>com.maciejwalkowiak.spring</groupId>
            <artifactId>wiremock-spring-boot</artifactId>
            <version>2.0.0</version>
            <scope>test</scope>
            <exclusions>                
                <exclusion>
                    <groupId>org.wiremock</groupId>
                    <artifactId>wiremock</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.wiremock</groupId>
            <artifactId>wiremock-standalone</artifactId>
            <version>3.3.1</version>
            <scope>test</scope>
        </dependency>

```
However, I don't know which drawbacks this brings with itself.

To be fair, this is definetly a wiremock problem. I just wanted to leave my solution here in case anyone else comes across this error.
And maybe to track the issue in the context of this repository.

**Comment by maciejwalkowiak** [comment]
Thanks for bringing it up. I am aware of this problem in Wiremock but haven't had time yet to update this project. I think standalone variant is safer anyway as it avoids any potential collisions on the class path.

**Comment by myou11** [comment]
Hi @maciejwalkowiak, I ran into this issue yesterday and was wondering if a new version could be pushed out for usage with springboot 3.2.x please?
