### ISSUE TITLE
port for Slf4jNotifier bug required

### ISSUE THREAD

**Issue by rfelgent** [maciejwalkowiak/wiremock-spring-boot#26]
Hi @maciejwalkowiak ,

when using the latest library `wiremock-spring-boot` I experience same issue as described in https://github.com/spring-cloud/spring-cloud-contract/issues/1916

Is there port missing ? 

Greetings

**Comment by maciejwalkowiak** [comment]
Thanks for reporting. Fixed and published in 2.1.2

**Comment by rfelgent** [comment]
thank you very much!
