### ISSUE TITLE
add support for multiple property injection

### ISSUE THREAD

**Issue by rfelgent** [maciejwalkowiak/wiremock-spring-boot#28]
Hi @maciejwalkowiak 

I would like to suggest one enhancement: introduction of multiple property mapping (instead of a single one):

This leads to a simplified setup, for example:

current, complex approach:

```
@EnableWireMock({
    @ConfigureWireMock(name = "product-aggregates-service", property = "app.client-apis.product-aggregates.base-path", configurationCustomizers = {WireMockCustomizer.class}),
    @ConfigureWireMock(name = "participations-service", property = "app.client-apis.participations.base-path", configurationCustomizers = {WireMockCustomizer.class}),
    @ConfigureWireMock(name = "businesspartners-service", property = "app.client-apis.businesspartners.base-path", configurationCustomizers = {WireMockCustomizer.class}),
    @ConfigureWireMock(name = "usageinformations-service", property = "app.client-apis.usage-informations.base-path", configurationCustomizers = {WireMockCustomizer.class})
})
```

new, simplified aproach:
```
@EnableWireMock({
    @ConfigureWireMock(name = "services",
         property = {
            "app.client-apis.product-aggregates.base-path"
            "app.client-apis.participations.base-path",      
            "app.client-apis.businesspartners.base-path",
            "app.client-apis.usage-informations.base-path"
         },
        configurationCustomizers = {WireMockCustomizer.class})
})
```

If you are convinced by that feature, I can try to make a PR

**Comment by maciejwalkowiak** [comment]
The `name` maps to configured WireMockServer instance, with an idea that each instance's base url is bound to a single property. Do you mean in your example that all of these base paths would have the same url?

**Comment by maciejwalkowiak** [comment]
@rfelgent go for it!

**Comment by rfelgent** [comment]
Hi @maciejwalkowiak  

when will you find the time to Look at the pull request?

Greetingz

**Comment by maciejwalkowiak** [comment]
Soonish, hopefully beginning of the next week

**Comment by rfelgent** [comment]
ping @maciejwalkowiak  :)

**Comment by rfelgent** [comment]
ping @maciejwalkowiak

**Comment by maciejwalkowiak** [comment]
@rfelgent Check PR. I've remembered about this PR, it just had to wait for its time. Pinging does not help 😉

**Comment by rfelgent** [comment]
Hi @maciejwalkowiak,

What is the current status?
