### ISSUE TITLE
`WireMock` naming collision

### ISSUE THREAD

**Issue by maciejwalkowiak** [maciejwalkowiak/wiremock-spring-boot#8]
There is a great likelihood that both `com.maciejwalkowiak.wiremock.spring.WireMock` and `com.github.tomakehurst.wiremock.client.WireMock` classes will be imported into a single file which forces user to use one of them with full qualified name. 

For example:

```
@com.maciejwalkowiak.wiremock.spring.WireMock("user-service")
private WireMockServer wiremock;
```

To avoid breaking change, there should be a new annotation introduced that will behave exactly the same as `com.maciejwalkowiak.wiremock.spring.WireMock` just with a different name.

Ideas:

- `@InjectWireMock`
- `@WireMocked`
- `@WireMockInstance`

Suggestions for name very welcome!

**Comment by SimonVerhoeven** [comment]
@InjectWireMock carries my preferences since it also has the lowest likelihood of people incorrectly autocompleting, and then scratching their head.

**Comment by gurukulkarni** [comment]
Maybe @Wiremocked ?
